Update CI ubuntu release version
Certain versions of sqlite3 have this error with the CTE used
in list_event_sequences:

sqlite3.OperationalError: circular reference: descs

I'm hoping this will fix that error.

In my development environment, I have sqlite3 3.40.1 which does not
show a problem here.